# Shared command-line environment. Optional work dependencies live privately.
brew 'coreutils'
brew 'findutils'
brew 'gnu-sed'
brew 'grep'
brew 'git'
brew 'gh'
brew 'less'
brew 'tmux'
brew 'neovim'
brew 'python'
brew 'direnv'
brew 'jq'
brew 'fzf'
brew 'shellcheck'
brew 'bash-completion@2'
brew 'zsh-completions'
